name: JARVYS-Dev Orchestration

on:
  schedule:
    - cron: '0 * * * *'   # toutes les heures (UTC)
  workflow_dispatch:

env:
  ImageName: jarvys-dev
  ImageTag: latest

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ env.ImageName }}:${{ env.ImageTag }} .

      - name: Run JARVYS-Dev container
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
        run: docker run --rm -e OPENAI_API_KEY -e GITHUB_TOKEN ${{ env.ImageName }}:${{ env.ImageTag }}
